# Generated by Django 4.2.10 on 2024-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_agent_name_event_initiated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="interaction_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
