# Generated by Django 4.2.10 on 2024-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_played",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_unread",
            field=models.BooleanField(default=True),
        ),
    ]
