# Generated by Django 4.2.10 on 2024-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_is_played_event_is_unread"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
