# Generated by Django 4.2.10 on 2024-05-09 11:46

from django.db import migrations


def forwards_func(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    db_alias = schema_editor.connection.alias
    events = Event.objects.using(db_alias).all()
    for event in events:
        # Transfer the source_user_id
        if event.source_user_id:
            event.src_user_id = event.source_user_id
        # Transfer the destination_user_id
        if event.destination_user_id:
            event.dest_user_id = event.destination_user_id
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_dest_user_event_src_user"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
