# Generated by Django 4.2.10 on 2024-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_interaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled call held"),
                    ("CALLED_US", "Called us"),
                    ("ANSWERED_OUR_CALL", "Answered our call"),
                    ("MISSED_OUR_CALL", "Missed our call"),
                    ("MISSED_THEIR_CALL", "Missed their call"),
                    ("SENT_US_AUDIO_NOTE", "Sent us audio note"),
                    ("WE_SENT_AUDIO_NOTE", "We sent audio note"),
                    ("LOGGED_IN", "Logged in"),
                    ("LEFT_WEBAPP", "Left webapp"),
                    ("DECLINED_CALL", "Declined call"),
                    ("CHECKIN_SKIPPED", "Checkin Skipped"),
                    ("CHECKIN_COMPLETED", "Checkin Completed"),
                    ("CHECKIN_NOT_APPLICABLE", "Checkin Not Applicable"),
                    ("SESSION_RECORDING", "Session Recording"),
                ],
                max_length=255,
            ),
        ),
    ]
