# Generated by Django 4.2.10 on 2024-02-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("pusher_channel_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pusherchannelapp",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pusher_channel_apps",
                to="user.organization",
            ),
        ),
    ]
