# Generated by Django 4.2.10 on 2024-03-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call Scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled Call Held"),
                    ("CALLED_US", "Called Us"),
                    ("ANSWERED_OUR_CALL", "Answered Our Call"),
                    ("MISSED_OUR_CALL", "Missed Our Call"),
                    ("MISSED_THEIR_CALL", "Missed Their Call"),
                    ("SENT_US_AUDIO_NOTE", "Sent Us Audio Note"),
                    ("WE_SENT_AUDIO_NOTE", "We Sent Audio Note"),
                    ("LOGGED_IN", "Logged In"),
                    ("DECLINED_CALL", "Declined Call"),
                ],
                default="Called Us",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="enduserlogin",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call Scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled Call Held"),
                    ("CALLED_US", "Called Us"),
                    ("ANSWERED_OUR_CALL", "Answered Our Call"),
                    ("MISSED_OUR_CALL", "Missed Our Call"),
                    ("MISSED_THEIR_CALL", "Missed Their Call"),
                    ("SENT_US_AUDIO_NOTE", "Sent Us Audio Note"),
                    ("WE_SENT_AUDIO_NOTE", "We Sent Audio Note"),
                    ("LOGGED_IN", "Logged In"),
                    ("DECLINED_CALL", "Declined Call"),
                ],
                default="Logged In",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call Scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled Call Held"),
                    ("CALLED_US", "Called Us"),
                    ("ANSWERED_OUR_CALL", "Answered Our Call"),
                    ("MISSED_OUR_CALL", "Missed Our Call"),
                    ("MISSED_THEIR_CALL", "Missed Their Call"),
                    ("SENT_US_AUDIO_NOTE", "Sent Us Audio Note"),
                    ("WE_SENT_AUDIO_NOTE", "We Sent Audio Note"),
                    ("LOGGED_IN", "Logged In"),
                    ("DECLINED_CALL", "Declined Call"),
                ],
                default="Call Scheduled",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="voicenote",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call Scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled Call Held"),
                    ("CALLED_US", "Called Us"),
                    ("ANSWERED_OUR_CALL", "Answered Our Call"),
                    ("MISSED_OUR_CALL", "Missed Our Call"),
                    ("MISSED_THEIR_CALL", "Missed Their Call"),
                    ("SENT_US_AUDIO_NOTE", "Sent Us Audio Note"),
                    ("WE_SENT_AUDIO_NOTE", "We Sent Audio Note"),
                    ("LOGGED_IN", "Logged In"),
                    ("DECLINED_CALL", "Declined Call"),
                ],
                default="Sent Us Audio Note",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("missed", "Missed"),
                    ("completed", "Completed"),
                ],
                default="Call Scheduled",
                max_length=20,
            ),
        ),
    ]
