# Generated by Django 4.2.10 on 2024-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_call_event_type_enduserlogin_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("missed", "Missed"),
                    ("completed", "Completed"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
