# Generated by Django 4.2.10 on 2024-03-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_meeting_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enduserlogin",
            name="event_type",
            field=models.CharField(default="Logged In", max_length=255),
        ),
    ]
