# Generated by Django 4.2.10 on 2024-03-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_officehours_organization"),
        ("home", "0004_alter_enduserlogin_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enduserlogin",
            name="end_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logins",
                to="user.enduser",
            ),
        ),
    ]
