# Generated by Django 4.2.10 on 2024-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_enduserlogin_end_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voicenote",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="voicenote",
            name="audio_file_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
