# Generated by Django 4.2.10 on 2024-03-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_voicenote_audio_file_voicenote_audio_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="voicenote",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
    ]
