# Generated by Django 4.2.10 on 2024-03-19 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_call_scheduled_time_alter_call_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="file_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="file_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scheduled_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
