# Generated by Django 4.2.10 on 2024-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_call_file_url_call_session_id_meeting_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduserlogin",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
