# Generated by Django 4.2.10 on 2024-03-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_voicenote_is_seen_enduser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="call",
            old_name="reciver",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="voicenote",
            old_name="reciver",
            new_name="receiver",
        ),
    ]
