# Generated by Django 4.2.10 on 2024-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_organization_enduserlogin_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
