# Generated by Django 4.2.10 on 2024-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_meeting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
