# Generated by Django 4.2.10 on 2024-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_meeting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CALL_SCHEDULED", "Call Scheduled"),
                    ("SCHEDULED_CALL_HELD", "Scheduled Call Held"),
                    ("CALLED_US", "Called Us"),
                    ("ANSWERED_OUR_CALL", "Answered Our Call"),
                    ("MISSED_OUR_CALL", "Missed Our Call"),
                    ("MISSED_THEIR_CALL", "Missed Their Call"),
                    ("SENT_US_AUDIO_NOTE", "Sent Us Audio Note"),
                    ("WE_SENT_AUDIO_NOTE", "We Sent Audio Note"),
                    ("LOGGED_IN", "Logged In"),
                    ("DECLINED_CALL", "Declined Call"),
                ],
                default="CALL_SCHEDULED",
                max_length=255,
            ),
        ),
    ]
