# Generated by Django 4.2.10 on 2024-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_meeting_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduserlogin",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
