# Generated by Django 4.2.10 on 2024-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_endusersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicenote",
            name="customer_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_enquiry", "Product Enquiry"),
                    ("customer_support", "Customer Support"),
                    ("otp_related_issue", "OTP Related Issue"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voicenote",
            name="page_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
