# Generated by Django 4.2.10 on 2024-03-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_client_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
