# Generated by Django 4.2.10 on 2024-03-07 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_organization_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime(2024, 3, 7, 14, 38, 27, 125626)
            ),
            preserve_default=False,
        ),
    ]
