# Generated by Django 4.2.10 on 2024-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_online_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
