# Generated by Django 4.2.10 on 2024-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_client_user_alter_enduser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
