# Generated by Django 4.2.10 on 2024-03-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officehours",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_hours",
                to="user.organization",
            ),
        ),
    ]
