# Generated by Django 4.2.10 on 2024-03-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_officehours_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarded_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="onboarded_organization",
                to="user.client",
            ),
        ),
    ]
