# Generated by Django 4.2.10 on 2024-03-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_organization_onboarded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="user.organization",
            ),
        ),
    ]
