# Generated by Django 4.2.10 on 2024-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_widget_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slack_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
