# Generated by Django 4.2.10 on 2024-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_organization_slack_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="slack_meta",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slack_token",
        ),
    ]
