# Generated by Django 4.2.10 on 2024-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_remove_organization_slack_meta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="enduser",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="enduser",
            name="linkedin",
            field=models.TextField(blank=True, null=True),
        ),
    ]
