# Generated by Django 4.2.10 on 2024-03-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_officehours_timezone_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_sent_after",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
