# Generated by Django 4.2.10 on 2024-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_organization_auto_sent_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="auto_sent_after",
            field=models.CharField(blank=True, default="", max_length=5, null=True),
        ),
    ]
