# Generated by Django 4.2.10 on 2024-03-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_organization_auto_sent_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="user.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="onboarded_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarded_organization",
                to="user.client",
            ),
        ),
    ]
