# Generated by Django 4.2.10 on 2024-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_enduser_welcome_note_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="auto_sent_after",
            field=models.CharField(blank=True, default="30", max_length=5, null=True),
        ),
    ]
