# Generated by Django 4.2.10 on 2024-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_organization_auto_sent_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
