# Generated by Django 4.2.10 on 2024-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_widget_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="avatar",
            field=models.CharField(
                choices=[("1", "Avatar 1"), ("2", "Avatar 2")], max_length=50
            ),
        ),
    ]
