# Generated by Django 4.2.10 on 2024-04-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_alter_widget_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enduser",
            old_name="trail_type",
            new_name="trial_type",
        ),
    ]
