# Generated by Django 4.2.10 on 2024-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_rename_trail_type_enduser_trial_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="avatar",
            field=models.CharField(
                choices=[("avatar1", "Avatar 1"), ("avatar2", "Avatar 2")],
                max_length=50,
            ),
        ),
    ]
