# Generated by Django 4.2.10 on 2024-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_featureflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="organization",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizations for whom the feature is enabled",
                related_name="feature_flags",
                to="user.organization",
            ),
        ),
    ]
