# Generated by Django 4.2.10 on 2024-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_featureflagconnect_delete_featureflag"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="is_new",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
