# Generated by Django 4.2.10 on 2024-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_enduser_is_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enduser",
            name="is_new",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
