# Generated by Django 4.2.10 on 2024-05-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_clientbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientbanner",
            name="banner_type",
            field=models.CharField(
                choices=[("ooo", "OOO"), ("info", "INFO")], default="ooo", max_length=50
            ),
        ),
    ]
