# Generated by Django 4.2.10 on 2024-05-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_clientbanner_banner_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_client_online",
            field=models.BooleanField(default=False),
        ),
    ]
