# Generated by Django 4.2.10 on 2024-05-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_client_is_client_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="check_in_status",
            field=models.CharField(
                choices=[
                    ("skipped", "Skipped"),
                    ("not_applicable", "Not Applicable"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="CheckInFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Modified Date",
                    ),
                ),
                ("master_switch", models.BooleanField(default=True)),
                ("skip_switch", models.BooleanField(default=False)),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=255),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_feature",
                        to="user.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
