# Generated by Django 4.2.10 on 2024-05-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_enduser_check_in_status_checkinfeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinfeature",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_in_feature",
                to="user.organization",
            ),
        ),
    ]
