# Generated by Django 4.2.10 on 2024-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="initial_events",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
