# Generated by Django 4.2.10 on 2024-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_usersession_initial_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="color_1",
            field=models.CharField(default="#3A4CF0", max_length=50),
        ),
        migrations.AddField(
            model_name="widget",
            name="color_2",
            field=models.CharField(default="#E01D5A", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
