# Generated by Django 4.2.10 on 2024-03-14 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0006_alter_client_user_alter_enduser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DyteMeeting",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Modified Date",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "meeting_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("meta_info", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dyte_meeting",
                        to="user.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DyteAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        null=True,
                        verbose_name="Modified Date",
                    ),
                ),
                ("token", models.TextField()),
                ("is_parent", models.BooleanField(default=True)),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("group_call_host", "Group Call Host"),
                            ("group_call_participant", "Group Call Participant"),
                        ],
                        default="group_call_participant",
                        max_length=255,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dyte_auth_tokens",
                        to="user.client",
                    ),
                ),
                (
                    "end_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dyte_auth_tokens",
                        to="user.enduser",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="auth_tokens",
                        to="dyte.dytemeeting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
