# Generated by Django 4.2.10 on 2024-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dyte", "0002_remove_dytemeeting_client_dytemeeting_end_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dyteauthtoken",
            name="auth_id",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
